# Lab culture {#lab-culture}

This chapter describes the structure and culture within the PALM Lab. The goal is to be clear about expectations for the members of the lab (ones that I have, as well as for each other) and importantly for myself.

> _This section aims to provide a picture of what mentoring and working with me will be like in the PALM Lab. It will continually be in-progress, shaped by (and including) feedback from lab members and others alike. -- William_

## Our lab environment {#lab-environment}

The lab should be a welcoming space for all members to work and conduct research. Everyone should be respectful and kind to each other, providing support and encouragement at all times. We are a team that shares in our successes, rather than competes with each other to get ahead (*and resists current incentive structures in science*). In fact, lab members are encouraged to take an interest in each others' work, learning from each other and collaborate on research.

Getting to know each other beyond being colleagues at work provides a strong basis for developing community within the lab. I encourage (and will help fund and/or organize) social events for the lab, but note that participation will always be optional. The goal is to have every member feel like they belong in the lab. (Note that I welcome any opportunity to take a quick break from work to grab a coffee and chat.)

> _I am mindful that conflicts may arise between lab members or with others externally. I will do my best to [mediate any issues](#conflicts) to the best resolution for all parties. To this end, I value clear communication - I will try my best to ensure the lab space is safe to bring up any disagreements or problems, especially so if they involve me. I hope that in a world that seems to be increasingly divided, we can nurture an environment that can resolve conflicts by listening to each other and having mutual resepct. -- William_

It is the responsibility of all lab members to keep the lab space organized and tidy, and to maintain a good working environment for all. This includes:

* Cleaning any rubbish or waste found in common spaces
* Putting lab equipment back in place after use
* Being considerate with shared spaces or resources (including dividing shared spaces or resources equitably, and communicating if something occurs that may impact others)
* Being mindful about taking up one's time or interrupting others' work in the lab (including the **volume of nearby conversations**)
* Taking an interest in other lab members' research projects (such as paying attention during talks or lab meetings)
* Offering to pilot each other's experiments or assist with data collection (such as gelling in EEG)

## Expectations about work {#lab-work}

It is important to maintain work-life balance (*in the face of capitalistic academic structures*) to ensure one's health, enjoyment in doing science, and to prevent burnout. Do prioritize taking breaks during the day or when you need them, managing life's responsibilities and keeping one's commitment to others. Remember that doing your best will look different on each day, it does not mean always working at full speed.

Full-time research is essentially equivalent to a full-time job (i.e. ~40 hours/week, 5 days per week). The PALM Lab adopts a 'hybrid model' where lab members are expected to spend at least three days of the week working on campus/in lab, and have the option to work either from home or in lab on the remaining days. The work hours themselves are somewhat flexible -- to ensure overlap between members in lab for collaboration and discussions, lab members are asked to have 10am to 3pm as part of their in-person hours. Ultimately, all lab members are responsible for managing and organizing their time to ensure research goals are met. You are not expected to work during evenings, weekends or public holidays. (*The one possible exception may be during critical deadlines, such as for conferences or grants. William will be as mindful as he can be of this, and if he does ask for something, you can be upfront and say it is not possible.*)

You are expected to stay home when you are sick, so that others (lab members, colleagues, participants) do not catch any illnesses. If this happens, please be mindful of others' time and reschedule any meetings as soon as you can.

> _I like to get out of the office and work at a nearby café - especially to code or write. It would be fun to co-work together as a lab! I find working with others keeps me accountable and productive. -- William_

### Requesting time off {-}

I trust lab members to be responsible for maintaining work hours and ensuring research progress is being made, and won't be strictly policing your hours. However, please check-in with me about taking any time off (mainly so that I am aware, as well as to make plans for your time away as needed). I recognise that there is more to life than science and research, so as a supervisor, I hope to make sure that there is balance (both enough work is being done and enough life is being lived.)

> _As your mentor, I will set regular (~weekly) check-in meetings with you to align expectations on what work needs to be achieved and if they are being met. These meetings will be an opportunity to communicate to me about any concerns or struggles, so that I am aware and can help support you or make plans to continue to make progress. -- William_

### Expectations around communication

Communication should always be with kindness and respectful of each other's time. General guidelines for various forms of communication are as follows:

* For most communication about lab-related matters, the PALM Lab uses **Slack**.
  * Slack can cause a lot of interruption to workflows. For this reason, it is not expected for Slack to be open at all times; it is recommended curating (or turning off) notifications to help maintain their focus on work. However, Slack should be checked periodically (~twice a day) to ensure no messages are missed.
  * The PALM Lab is on the free plan of Slack, which means **message history is restricted to 90 days**. As a result, communication in Slack should mostly be one-off in nature (quick questions/brief check-ins/notifications). Lab members are expected to maintain good organizational and note-taking practices for their projects.
  * Lab members are encouraged to set statuses (e.g. *do not disturb*, *in lab*, *working from home*, *on holiday*). I will also set statuses for a quick sign of his availability (e.g. *in office*, *teaching*, etc.).
* For any important communication (e.g. anything that might need documentation/record-keeping, such as where a decision is being made) or any messaging with a large group or external collaborators, use email.
  * Remember to be mindful of email etiquette - try to avoid spam by batching multiple questions into the one email, keeping them within the one thread.
* I will try to organise in-person meetings (~weekly) for discussing research projects (i.e. ideation, results, etc.). I might drop by the lab sporadically to check-in with whoever is around (and will try to be mindful of placing pressure on being in lab.)
* **For emergencies, do not hesitate to contact William by phone.**

### Making mistakes {-}

An important part of our lab culture (and science overall) is our attitude and response towards mistakes. In the PALM Lab, we recognize that mistakes (small or large) can happen despite our best efforts, and that it is unhelpful to respond poorly and place blame. We all make mistakes! In fact, mistakes should be treated as moments that one can grow from, and that others can learn from when we share them. I will make an effort to lead by example and share both present and past mistakes that he has made!

As a lab, we will prioritize careful, rigorous research rather than speedy, flashy research outputs, committing to open scholarship (see our [approach to Open Science in the next chapter](#open-science)). This means that we take additional steps towards preventing mistakes (for example, piloting experiments and code review). Nevertheless, sometimes mistakes can (and will) pop up. The members of the PALM Lab will be encouraged to take ownership of their mistakes - not to hide them but share and work through them with others (especially when it impacts others, or influences the research outcomes).

> _Some mistakes can *feel* very big - for example, a bug in the experiment means a large amount of time and resources have been wasted, or an incorrect analysis changes the results of the experiments dramatically - but these things do happen in science! I believe one should be challenging themselves and putting themselves in positions to make mistakes and fail, because that leads to growth. Any mistake that happens in the lab will partly be my own, so I hope you feel that you can share them with me when they do happen. What's most important is to correcting the mistakes in a transparent manner together. -- William_

## Mentorship {#lab-mentorship}

Lab members are encouraged to seek mentorship from many people and places, such that they learn from a diverse set of perspectives and experience. This could be from a senior graduate student or postdoc in the PALM Lab or in another lab, from a research collaborator or co-supervisor, and of course, from myself. All PALM Lab members are recommended to think about what **skills** they would like to learn, what **goals** they have in life and in science, and what may be an **inspiration** to them, and to seek out mentors who can help them with that (*it may not always be me!*).

### Expectations for William as a research supervisor {#will-mentor}

I am expected to provide mentorship that includes:

* Research training on experimental design, programming, data collection, data management, statistical analysis, computational modeling, manuscript writing, open scholarship, and further.
* Providing feedback in a timely manner (such as comments on project ideas, approval on conference submissions, suggestions on talks, edits on manuscripts, etc.)
* Giving thoughtful advice on and provide opportunities for achieving future success and preparing you for your the next step in your career (in science/academia or otherwise)
* Creating a healthy learning environment that encourages you to attempt things yourself and to fail at, asking questions without judgment and gives you the space to develop
* Being accessible both in-person and virtually (e-mail or otherwise), including regular meetings to discuss research (or anything else)

> _I hope to be a supportive supervisor for all PALM Lab members, fostering a working relationship that lasts throughout their journey in academia and science._
>
> _I will help all mentees navigate the obstacles and challenges of academia as best I can, and I hope to set an example of how to conduct impactful and rigorous science, through open scholarship practices and service for the community. -- William_

#### Mentorship style {-}

I will always strive for my mentees to achieve success towards their goals. I try to balance being a hands-on supervisor (for example, getting involved with programming, data collection, data analysis, and further), while encouraging independence and self-directed learning. I operate on a so-called 'open-door' model -- lab members are encouraged to reach out to me with any questions at any time, and to openly ask for the support they need. This includes, where appropriate, emotional support and encouragement while navigating challenges in science and academia.

I think I am fairly flexible in mentoring style, adapting to the mentee -- lab members are encouraged to 'mentor up' [(see this useful guide on mentoring up by Lee et al.,  p.141)](https://graduateschool.syr.edu/wp-content/uploads/2017/03/Lee-et-al..pdf). This includes discussing and aligning expectations, asking for and accepting advice and feedback, and having a roadmap for personal development (which I could help you plan!). You can also read more on [expectations of students below](#student-expectations).

You can find out a little bit more about me on [my personal academic website](https://williamngiam.github.io).

#### Weaknesses {-}

> _I believe one key characteristic of a good scientist is their humility, because it goes hand in hand with accepting one's imperfections and being open to change. I acknowledge that I have weakenesses and imperfect understsanding, which I list below so that you are better aware when working with me. -- William_

* I set a high standard of science for myself and the work that I am involved in -- one that goes beyond the norm for the field. For example, I take the additional steps of code review, reproducibility checks, replication of experiments and preparation of data for open access, rather than seeing the end goal as a publication. This high standard can put pressure on my collaborators - for example, rethinking how things are being done and potentially slowing research outputs from reaching stages of progress.
* I can see that this high standard might mean I appear overly critical, especially if I were to give critique without kindness or not to voice any positive feedback. My past mentees have not voiced this concern, but please do not hesitate to remind me to say what went well!
* As I am newly starting the PALM Lab, I am inexperienced with conducting research specifically at the University of Adelaide, and am yet to secure my own external research funding.
* I have a tendency to overcommit, having trouble saying 'no' when new opportunities arise. This may mean I am spread thin at times, leading to less timely responses or feedback.
* I value work-life balance, but do go through phases where I am doing 'work' late or on weekends -- I am usually reading related papers, or getting fixated on fixing programming issues or solving other problems. This may lead to message or responses at odd times, which I hope does not lead to the expectation that you should also work odd hours. (I will be very clear about this!)

## Expectations for PhD students {#student-expectations}

_under construction - waiting on getting to UofA!_

## Expectations for Honours students

_under construction_

## Resolving conflicts {#conflicts}

Conflicts within the lab or with others can occur despite our best intentions and efforts to prevent them. The hope is that conflicts will be resolved through listening to each other, understanding each other's perspective and respectfully reaching an agreed upon course of action.

If there is any potential for disagreement or unhappiness that cannot be resolved by discussing with the other party, the first person to talk to is me However, if I do not seem to be the right person (or the conflict is sourced by or with me), then the following contacts may be helpful:

* If you are a PhD student, the members of your thesis committee or the Dean of Learning
* If you are not a PhD student, seek out ....

_under construction_