# Research Policies

## Academic integrity

A core value of the PALM Lab and the University of Adelaide is to conduct scientific research with integrity. Lab members are expected to comply with the [University of Adelaide's Responsible Conduct of Research Policy](https://www.adelaide.edu.au/policies/96/). Research misconduct, such as fabrication (*making up data or results*), falsification (*changing or omitting methods or data such that the research record is inaccurate*), or plagiarism (*taking another person's ideas or results without appropriate credit*) will not be tolerated. Lab members are encouraged to read these research policies and ask William if they have any questions. 

Research fraud is entirely antithetical to the PALM Lab's commitment to benefit society by working towards the truth through rigorous and transparent research. There is no excuse for research fraud - it risks one's career, is a disservice to the field, and undermines society's trust in science. 

> _Scientists are typically evaluated on the number of research publications, and the prestige of the journals they are published in. These incentives may compel someone to conduct research misconduct -- to speed up research and/or to produce a notable finding. Simply put, research misconduct and fraud is not right, and never worth it -- it will be discovered (*if not by the PALM lab prior to publication*) and jeopardize any success one may have hoped to get, and it will cause substantial costs to the field and society._
>
> _I have a different definition of research success that I hope you will learn to share - in brief, I believe the best science will include thoughtfulness of the experimental design, transparency of the research process, availability of the code and the data, reliability of the findings, positive impact on society, and much more. I hope that you will pursue research with these values foremost. -- William_

Any concern of research misconduct within the PALM Lab should be reported to William immediately, who will act according to the [University of Adelaide's Research Misconduct Procedure (2019)](https://www.adelaide.edu.au/policies/96/?dsn=policy.document;field=data;id=7885;m=view) on how complaints of research misconduct will be handled and investigated. Further resources can be found on the [University of Adelaide's page on Research Integrity](https://www.adelaide.edu.au/staff/research/ethics-compliance-integrity/research-integrity).

## Contributorship, not authorship {#contributorship}

In psychology and neuroscience, scientists are recognized through authorship on scientific publications. Being the **first author** of a publication signifies being the lead researcher and main contributor on the project, whereas the **last author** denotes the senior researcher on the project. In the remaining positions (second to second-last), order of authorship typically by (perceived) amount of contribution to the project.

Current standards for authorship (such as by the [International Committee of Medical Journal Editors](https://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html) and the [American Psychological Association](https://www.apa.org/research/responsible/publication)) require a writing contribution to the research publication. Instead, the PALM Lab believes that **all researchers contributing to a scientific publication should be recognized** ("a contributorship model"), and adopts the [Contributor Roles Taxonomy (CRediT)](https://credit.niso.org/) to assign credit and authorship. CRediT lists 14 research roles that contribute to research outputs, listed below with brief explanations as how they might pertain to the PALM Lab:

* **Conceptualization** - The **formulation** or evolution of overarching research goals and aims.
* **Data curation** - Data **management**, including generating metadata, cleaning and maintaining research data
* **Formal analysis** - Application of statistical, mathematical, and/or computational techniques to **analyse experimental data**.
* **Funding acquisition** - Acquisition of the financial support for conducting the research
* **Investigation** - **Conducting the experiments** for data collection
* **Methodology** - **Design** of the experiment
* **Project administration** - **Coordination** of the research activity
* **Resources** - **Provision** of any equipment
* **Software** - **Programming** and testing of experimental code.
* **Supervision** - **Oversight** for the research activity, including mentorship.
* **Validation** - **Verification** of the overall reproducibility of results/experiments.
* **Visualization** - **Preparation** of the published work, specifically data presentation. 
* **Writing -- original draft** - Preparation of the initial draft.
* **Writing -- review and editing** - Critical review, commentary or revision.

The standard for authorship on any research publication from the PALM Lab is to have adequate involvement in **at least one** of the above roles, with the following as minimum requirements:

* **Investigation** - The researcher was responsible for data collection of at least a third (1/3) of the sample size in any experiment. (Assistance with EEG preparation does not count towards this.)
* **Validation** - Conducted code review at least once, producing a report on the computational reproducibility of the results and experiment.
* **Writing** - Provided comments or suggestions that both the first author and William agrees made a significant impact on the communication of the ideas or results. That is, the review went beyond grammatical edits or syntax changes.

If not explicitly required by the journal, the CRediT contributions will be listed in the acknowledgements or footnotes of all research outputs of the PALM Lab (see [the tenzing app](#tenzing). The first author is expected to **take ownership** of the research project and have contributed to the majority of these roles, likely *conceptualization, data curation, formal analysis, investigation, project administration, software, visualization, writing -- original draft and writing -- review and editing*. In rare circumstances, there may be two or more authors that warrant lead authorship on a research publication, which may be recognized with co-first authorship. Order of authorship (other than first and senior) may be decided by counting the number of *major* contributions made in each of the roles.

Authorship should be discussed as early as possible (such as at the beginning of a research project), so that expectations are aligned and contributions are equitably recognized for all. There are potential unforeseen circumstances that may lead to uncertainty about whether a researcher should be recognized with authorship - in these circumstances, the decision ultimately rests with the first author and William (who will lean towards inclusive authorship). In discussion with relevant parties, lead (first) authorship will be passed on if the responsibility for a research project (*data, analyses and results*) is given to someone else (for example, if a lab member collected an experimental dataset but is unlikely to complete the analysis and publish the research). William will likely be the senior (final) author on the manuscript, if the research is primarily conducted within the PALM Lab.

You can view the University of Adelaide's Authorship Policy at [this link](https://www.adelaide.edu.au/policies/3503). Disputes over authorship can arise, and their resolution may require mediation from the Research Integrity Advisor ([Professor Carolyn Semmler](https://researchers.adelaide.edu.au/profile/carolyn.semmler)), the Postgraduate Coordinator ([Associate Professor Diana Dorstyn](https://www.adelaide.edu.au/directory/diana.dorstyn))

## Open Science {#open-science}

The PALM Lab aims to conduct rigorous and transparent research through Open Science practices. With William's guidance, each lab member is encouraged to pursue the following research practices as best as they can. Note that this is not an all-or-none expectation - Open Science is like a buffet, where scientists should strive to do what they can (Bergmann)

### Preregistrations (and Registered Reports)

Preregistration is the practice of creating a public, timestamped record of one's experimental design and intended analyses **prior to** data collection. It is intended to promote the transparency of one's research and prevent questionable research practices like *p*-hacking and *HARK*ing. In a Registered Report format, the preregistration is peer-reviewed (known as Stage 1 of the Registered Report). Once accepted, the results will be published in-principle by the journal if the preregistration was followed.

Preregistration can be a useful practice because it necessitates clear rationales for decisions that are made in the research design process, curbing the potential to make idiosyncratic choices. This can help research students get on the same page as research supervisors (i.e. William) on the aims of the research project, and to understand the reasons for the approach being taken.

PhD students and postdocs in the PALM Lab are encouraged to draft preregistrations with William (even if not intending to publish them) on the [Open Science Framework (OSF) Registries](https://osf.io/registries/osf/new). Honours students are not expected to draft preregistrations for the sake of timeliness of their empirical research project (though it may still be a useful exercises for writing the eventual thesis.)

### Sharing experiment code and data

The PALM Lab aims to share all experimental code and data associated with research publications to promote reproducibility of the findings. In brief, open code and data allow peer reviewers to attempt empirical and/or computational reproductions of the projects, ensuring the rigor and credibility of the research, as well as enable secondary uses to increase the overall efficiency of science.

With William's guidance, all lab members are encouraged to write transparent code and manage data with the expectation that it will be publicly available when submitting the research manuscript for publication. (See [Wilson et al., 2017 for good enough practices for scientific computing](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)). The (de-identified) experiment data and code (both experiment and analysis) will be uploaded to the [Open Science Framework](https://osf.io). Neuroimaging (EEG) data may be uploaded to [OpenNeuro](https://openneuro.org/) which requires the [Brain Imaging Data Structure (BIDS)](https://bids.neuroimaging.io/) format for data storage. See [this OSF repository](https://osf.io/wjr7u/) for an example of a code and data repository.

The University of Adelaide provides support on achieving [FAIR (*findable, accessible, interoperable and reusable*) data](https://www.adelaide.edu.au/library/library-services/services-for-researchers/fair), including this [Research Data Planner](https://www.adelaide.edu.au/technology/research/research-data/research-data-planner) tool.  

### Preprints (and conference presentations)

For the quick dissemination of research, the PALM Lab will upload preprints of research manuscripts. These will be uploaded to the [PsyArXiv](https://psyarxiv.com) server, with links to any associated OSF repositories. The preprints (and any associated conference presentations) will also be made available on the [PALM Lab website](https://palm-lab.github.io/presentations). PALM Lab members will be recommended to upload the preprint alongside submitting their manuscript for publication at a scientific journal.

