# Lab Resources

This chapter provides useful links to software and associated resources for conducting research in the PALM Lab. The following is not a strict list; lab members are encouraged to explore what tools and resources are out there, especially open source software, to keep current with research.

## Required

The following resources will likely be needed for conducting research in the PALM Lab.

### MATLAB (or Python) {-}

The code for conducting the experiments and data analysis will mostly be written in MATLAB. The University of Adelaide provides [access to download and use the licensed software](https://www.mathworks.com/academia/tah-portal/university-of-adelaide-30536634.html). 

If a lab member is an experienced programmer (i.e. requiring *not as much* coding supervision from William), they can opt to write their experimental and analysis code in [**Python**](https://www.python.org/), an open source software with numerous well-maintained packages for scientific research.

#### PsychToolbox (or PsychoPy) {-}

[PsychToolbox](http://psychtoolbox.org/) is the software package we use for building psychology experiments (i.e. displaying stimuli and collecting responses) in MATLAB. A useful set of demos can be found on [Peter Scarfe's lab website](https://peterscarfe.com/ptbtutorials.html). The Python alternative is [PsychoPy](https://www.psychopy.org/).

#### EEGLAB {-}

[EEGLAB](https://sccn.ucsd.edu/eeglab/index.php) is the software we use for analysing electroencephalography (EEG) data within the MATLAB environment. EEGLAB provides a point-and-click interface to conduct most EEG analyses (such as calculating event-related potentials), as well as the base functions for custom analysis scripts. Our artifact rejection pipeline can be found on Github.

[An introduction to the event-related potential by Steve Luck](https://mitpress.mit.edu/9780262525855/an-introduction-to-the-event-related-potential-technique/) is a good starting point for learning about EEG and various event-related potentials.

### R and RStudio {-}

To run some statistical analyses, we may use R and [RStudio](https://posit.co/download/rstudio-desktop/).

[R for Data Science by Hadley Wickham](https://r4ds.hadley.nz/) is a free book that is a great introduction into using R for data analysis and visualization.

### Github and Github Desktop {-}

For code management and version control, the lab uses Git and [Github](https://github.com). The [PALM Lab's Github](https://github.com/PALM-Lab) will contain all code repositories for our lab, including shared packages for our common processing or analyses (such as artifact rejection of EEG). 

Github's [own start-up guide](https://docs.github.com/en/get-started/quickstart/hello-world) is a good place to learn how to use Github. For those less experienced with programming, [Github Desktop](https://desktop.github.com/) is an easy-to-use interface for maintaining code between your local computer and Github.

## Recommended

### Zotero {-}

[Zotero](https://www.zotero.org/) is a desktop software app for organizing scientific papers and managing references. It has an in-built PDF reader with tools for annotations and note-taking, and plug-ins for inserting references and bibliographies into manuscripts.

[Zotero Connector](https://www.zotero.org/download/connectors) is a very useful Google Chrome extension for adding journal articles directly into Zotero from Google Scholar or journal webpages. This plug-in will also connect Zotero to Google Docs, enabling adding citations and bibliographies into any working manuscript (which can be ported to Microsoft Word at any time). An [additional extension](https://www.zotero.org/support/word_processor_plugin_usage) is needed to connect Zotero to Microsoft Word.

### Jamovi or JASP {-}

[JASP](https://jasp-stats.org/) and [Jamovi](https://www.jamovi.org/) are free, open-source statistical software programs that provide a point-and-click interface for conducting both frequentist and Bayesian statistical analyses.

### Tenzing {-#tenzing}

[*Tenzing*](https://tenzing.club) is an easy-to-use web app for quickly generating the author list, their affiliations and their contributions according to the Contributor Roles Taxonomy (CRediT). The PALM Lab uses a [policy of contributorship](#contributorship) to credit researchers. Use *tenzing* to generate the CRediT roles prior to the submission of a research manuscript for publication.

The app was created by Alex Holcombe, Marton Kovacs, Frederik Aust and Balazs Aczel. See [Holcombe, A. O., Kovacs, M., Aust, F., & Aczel, B. (2020). Documenting contributions to scholarly articles using CRediT and tenzing. PLoS ONE, 15(12), e0244611.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0244611).

## Optional

### Obsidian {-}

[Obsidian](https://obsidian.md/) is a note-taking and knowledge management software that is designed to be a 'second brain' for the user. Notes are written and saved as Markdown files, and with the use of tags, links and community-built plugins, Obsidian can provide a powerful organization and navigation of the notes. Obsidian does have a steep learning curve and requires some setting up (including thought about structure and organization) before it can work well.

### Adobe Illustrator {-}

Adobe Illustrator is part of the Adobe Creative Cloud, and is useful for editing and cleaning up scientific figures for publication (for example, *generating vector graphics to the appropriate sizes*), and for creating well-designed conference posters. 

Additional resources (mostly educational in nature) can be found in [Chapter 6](#extra-resources).
